export const LOGGED_SUCCESSFULLY = 'LOGGED_SUCCESSFULLY'
export const LOGGED_FAILED = 'LOGGED_FAILED'
export const LOGOUT = 'LOGOUT'
export const LOGGING_ATTEMPT = 'LOGGING_ATTEMPT'

export const HEADER_TITLE = 'HEADER_TITLE'
export const SIDEBAR_MENUS = 'SIDEBAR_MENUS'
export const SIDEBAR_INVISIBLE = 'SIDEBAR_INVISIBLE'

export const FETCH_USER = 'FETCH_USER'
export const FETCH_COMPANY = 'FETCH_COMPANY'
export const FETCH_SUBSCRIPTION = 'FETCH_SUBSCRIPTION'

export const SET_FORMS_ORDER = 'SET_FORMS_ORDER'
export const FETCH_INVENTORY = 'FETCH_INVENTORY'
export const SHOW_INVENTORY = 'SHOW_INVENTORY'
export const STORE_INVENTORY = 'STORE_INVENTORY'

export const FETCH_CATEGORIES = 'FETCH_CATEGORIES'
export const SHOW_CATEGORIES = 'SHOW_CATEGORIES'
export const STORE_CATEGORIES = 'STORE_CATEGORIES'
export const UPDATE_CATEGORIES = 'UPDATE_CATEGORIES'
export const DELETE_CATEGORIES = 'DELETE_CATEGORIE'

export const FETCH_MODELS = 'FETCH_MODELS'
export const SHOW_MODELS = 'SHOW_MODELS'
export const STORE_MODELS = 'STORE_MODELS'
export const UPDATE_MODELS = 'UPDATE_MODELS'
export const DELETE_MODELS = 'DELETE_MODELS'
